"""
Django settings for user_manager project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*#0udd5612&!@)p)()t7y8$-+-$(o#t^qnz56+s6#pp$5ia3*2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['wa.a1s.kz']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",

    #My apps
    'core',
    'wa_inbox',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://email.a1s.kz",
    "http://email.a1s.kz",
    "https://wa.a1s.kz",
    "http://wa.a1s.kz",
]

CORS_ALLOW_CREDENTIALS = True

# Allow custom auth headers so frontend can send X-WA-Inbox-Token (and API key) without CORS blocking.
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-language",
    "content-language",
    "content-type",
    "authorization",
    "x-wa-inbox-token",
    "x-wa-inbox-api-key",
]

# Required in Django 4+ when frontend (e.g. localhost:3000) POSTs to this backend.
# Otherwise: "Origin checking failed - http://localhost:3000 does not match any trusted origins."
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://wa.a1s.kz",
    "http://wa.a1s.kz",
]

ROOT_URLCONF = 'user_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Auth: where to send users when login_required redirects (e.g. /wa-inbox/ -> /login/?next=/wa-inbox/)
LOGIN_URL = "/login/"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = '/Users/karen/Desktop/Developer/CRM/staticfiles'
STATIC_ROOT = '/home/ubuntu/CRM_Eduverse/staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email service
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'support@eduverse.kz'
EMAIL_HOST_PASSWORD = 'wiapiflevprmobaq'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# URL of the email-builder app (for "Build new" / "Edit in builder" links)
EMAIL_BUILDER_URL = "https://email.a1s.kz"

# WhatsApp Team Inbox (WhatsAppFront) – URL of the Next.js frontend.
# Use for one WhatsApp shared across departments.
# For session login to work (no 401), frontend must be on the SAME domain as the CRM
# (e.g. both https://wa.a1s.kz). Dev with different origins (e.g. frontend :3000, CRM :8000)
# will get 401 until deployed same-origin. Production: set to e.g. "https://wa.a1s.kz"
WA_INBOX_FRONTEND_URL = "http://localhost:3000"

# Green API for wa_inbox poller (management command wa_inbox_poll_green).
# Use same instance/token as the bot so messages are stored in CRM Contact + Message.
GREEN_API_INSTANCE = "waInstance7103440972"
GREEN_API_TOKEN = "7833fac0e9ec4bf3b114d58c87411cec62e741f5c31c452885"

# Optional: require this header on POST /wa-inbox/api/record-message/ (bot pushing to CRM).
# WA_INBOX_API_KEY = "your-secret-key"