# Generated by Django 4.2.27 on 2026-01-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('results', models.TextField()),
                ('note', models.TextField(null=True)),
                ('grade', models.IntegerField()),
                ('school', models.CharField(max_length=150)),
                ('countryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Лид', 'В работе'), ('Акт', 'Активный'), ('Арх', 'Архив')], default='Лид', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='core.product')),
            ],
        ),
    ]
