# Generated by Django 4.2.27 on 2026-01-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='participant_id',
            field=models.IntegerField(),
        ),
    ]
