# Generated by Django 4.2.27 on 2026-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_participant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Лид', 'В работе'), ('Акт', 'Подтвердил'), ('Арх', 'Отказ')], default='Лид', max_length=30),
        ),
    ]
