# Generated by Django 4.2.27 on 2026-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('idInstance', models.CharField(max_length=10)),
                ('apiTokenInstance', models.CharField(max_length=50)),
            ],
        ),
    ]
