# Generated by Django 4.2.27 on 2026-02-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.product'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Лид', 'В работе'), ('Дум', 'Думает'), ('Акт', 'Подтвердил'), ('Арх', 'Отказ')], default='Лид', max_length=30),
        ),
    ]
