# Generated by Django 4.2.27 on 2026-02-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_id',
        ),
    ]
