# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("tags", models.JSONField(default=list, help_text="List of tag strings")),
                ("status", models.CharField(choices=[("NEW_LEAD", "New Lead"), ("QUALIFYING", "Qualifying"), ("WAITING_PAYMENT", "Waiting Payment"), ("ENROLLED", "Enrolled"), ("SUPPORT_NEW", "New Ticket"), ("SUPPORT_IN_PROGRESS", "In Progress"), ("WAITING_CLIENT", "Waiting Client"), ("RESOLVED", "Resolved"), ("PAYMENT_ISSUE", "Payment Issue"), ("REFUND_REQUEST", "Refund"), ("ESCALATED", "Escalated"), ("SPAM", "Spam"), ("CLOSED", "Closed")], default="NEW_LEAD", max_length=32)),
                ("department", models.CharField(choices=[("MANAGER_DANA", "manager Dana"), ("MANAGER_SABINA", "manager Sabina"), ("MANAGER_FANIYA", "manager Faniya")], default="MANAGER_DANA", max_length=32)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("MED", "Medium"), ("HIGH", "High")], default="MED", max_length=8)),
                ("last_message", models.TextField(blank=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("last_outbound_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("sla_state", models.CharField(choices=[("OK", "OK"), ("WARNING", "Warning"), ("BREACHED", "Breached")], default="OK", max_length=16)),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Contact",
                "verbose_name_plural": "WhatsApp Contacts",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("direction", models.CharField(choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")], max_length=8)),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("status", models.CharField(blank=True, choices=[("sending", "Sending"), ("sent", "Sent"), ("delivered", "Delivered"), ("read", "Read"), ("failed", "Failed")], max_length=16, null=True)),
                ("attachments", models.JSONField(blank=True, default=list, help_text="List of {type, url, name}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="wa_inbox.contact")),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "ordering": ["timestamp"],
            },
        ),
    ]
