# Generated by Django 4.2.27 on 2026-03-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_client_user_id'),
        ('wa_inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_inbox_contacts', to='core.crm_user'),
        ),
    ]
