# Generated by Django 4.2.27 on 2026-03-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_client_user_id'),
        ('wa_inbox', '0002_contact_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wa_inbox.contact')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_inbox_notes', to='core.crm_user')),
            ],
            options={
                'verbose_name': 'Internal Note',
                'verbose_name_plural': 'Internal Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
