# Generated by Django 4.2.27 on 2026-03-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wa_inbox', '0003_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('TRANSFERRED', 'Transferred'), ('STATUS_CHANGED', 'Status changed'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('NOTE_ADDED', 'Note added'), ('TAG_CHANGED', 'Tags changed')], max_length=32)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wa_inbox.contact')),
            ],
            options={
                'verbose_name': 'Contact history event',
                'verbose_name_plural': 'Contact history',
                'ordering': ['-created_at'],
            },
        ),
    ]
